### ISSUE TITLE
Dragging component

### ISSUE THREAD

**Issue by MikeGsus** [envyN/ngx-widget-grid#15]
**Select one ...**  (check one with "x")
   ```
   [ ] bug
   [x] feature request
   [ ] enhancement
   ```
   
   ### Expected behavior
   
   When a widget is moved others must move too, for the dynamic ordering of the components on the grid
   
   ### Actual behavior
   
   When a widget is dragged, just this is moved. The others widget keep theirs places, no matter if the dragged component is placed over them.
   
   ### Environment details
   
   * **Angular version:** 6.1.10
   
   * **OS and version:** Windows 8.1
   
   * **Browser:** [ Chrome 70.0.3538.110, Firefox 63.0.3  ]

**Comment by envyN** [comment]
HI @MikeGsus ,
The library was developed with the intention to be a fixed dimension layout. Hence there is a limit to the number of widgets that could be added to an instance of the grid.
Your ask is something like what other grid libraries do which push other widgets down.
Now since in this library both width and height is pre-determined/ hard-bound, it is not feasible to bring in this feature which does auto push-down of other widgets.
