### ISSUE TITLE
position is not working

### ISSUE THREAD

**Issue by Chinna2405** [envyN/ngx-widget-grid#23]
[ x] bug
   [ ] feature request
   [ ] enhancement
   ```
   

   When assigning a position in a function in typescript file the position is not reflected in the browser.
   

Thanks in Advancd

   ### Environment details
   
   * **Angular version:** 8.x.x
   
   * **OS and version:** 
   
   * **Browser:** [all | Chrome XX | Firefox XX | IE XX]

**Comment by Chinna2405** [comment]
Please refer this below link for the issue.
https://angular-budy4p.stackblitz.io/
On clicking the Compress button it should again retain the old position that is available in the 'newPosition' variable

**Comment by envyN** [comment]
@Chinna2405 though ideally, you should be dealing with configuration objects which store the state of the widgets, for your particular stackblitz, i have modified the code a bit:

https://stackblitz.com/edit/angular-budy4p?file=src%2Fapp%2Fapp.component.ts

Essentially, since the position attribute is mutated by the library, you should persist the changes by cloning the objects whenever needed.
Also, since you are changing the grid row/column configuration, while simultaneously updating the widget positions, it becomes necessary to call the grid components updateRendering method for your changes to become visible.

There is also this fork of your app which doesnt change the grid configuration to 1:1 from 4:5 while expanding/compressing.
https://stackblitz.com/edit/angular-ybex8u?file=src%2Fapp%2Fapp.component.ts
